name: Build image and push to ECR

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-west-2"
      
jobs:
  # Job : Deploy the application (Depends on 'create-infra' job)
  deploy-app:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::711387104213:role/aws-auth
          aws-region: us-west-2
          id-token: true
    

      - name: Create ECR
        run: |
          aws ecr create-repository --repository-name patient-service
          aws ecr create-repository --repository-name appointment-service

      # Step 3: Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-west-2

      # Step 5: Build patient-service Docker image
      - name: Build patient-service Docker image
        run: |
          docker build -t 711387104213.dkr.ecr.us-west-2.amazonaws.com/patient-service:latest -f app/patient-service/Dockerfile app/patient-service

      # Step 6: Build appointment-service Docker image
      - name: Build appointment-service Docker image
        run: |
          docker build -t 711387104213.dkr.ecr.us-west-2.amazonaws.com/appointment-service:latest -f app/appointment-service/Dockerfile app/appointment-service

      # Step 7: Push patient-service Docker image to ECR
      - name: Push patient-service Docker image to ECR
        run: |
          docker push 711387104213.dkr.ecr.us-west-2.amazonaws.com/patient-service:latest

      # Step 8: Push appointment-service Docker image to ECR
      - name: Push appointment-service Docker image to ECR
        run: |
          docker push 711387104213.dkr.ecr.us-west-2.amazonaws.com/appointment-service:latest
